import '../models/question.dart';

const List<Question> questionBank = [
  // ===== KHÁI NIỆM VÀ QUY TẮC =====
  Question(
    id: 1,
    content: 'Làn đường là gì?',
    options: [
      'Phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn',
      'Phần đường dành cho người đi bộ',
      'Phần đường dành riêng cho xe máy',
      'Phần đường giữa hai vạch kẻ đường',
    ],
    correctIndex: 0,
    explanation: 'Làn đường là phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn.',
    category: 'Khái niệm',
  ),
  Question(
    id: 2,
    content: 'Người điều khiển xe mô tô phải đội mũ bảo hiểm trong trường hợp nào?',
    options: [
      'Chỉ khi đi trên đường cao tốc',
      'Khi đi trên đường có tốc độ cao',
      'Khi tham gia giao thông trên đường bộ',
      'Chỉ khi trời mưa',
    ],
    correctIndex: 2,
    explanation: 'Người điều khiển, người ngồi trên xe mô tô, xe gắn máy phải đội mũ bảo hiểm có cài quai đúng quy cách khi tham gia giao thông trên đường bộ.',
    category: 'Quy tắc giao thông',
    isCritical: true,
  ),
  Question(
    id: 3,
    content: 'Tốc độ tối đa cho phép xe mô tô trong khu vực đông dân cư là bao nhiêu km/h?',
    options: ['40 km/h', '50 km/h', '60 km/h', '70 km/h'],
    correctIndex: 1,
    explanation: 'Tốc độ tối đa cho phép xe mô tô trong khu vực đông dân cư là 50 km/h.',
    category: 'Tốc độ',
  ),
  Question(
    id: 4,
    content: 'Biển báo cấm nào sau đây cấm xe mô tô đi vào?',
    options: [
      'Biển "Cấm ô tô"',
      'Biển "Cấm xe cơ giới"',
      'Biển "Cấm xe tải"',
      'Biển "Cấm xe đạp"',
    ],
    correctIndex: 1,
    explanation: 'Biển "Cấm xe cơ giới" cấm tất cả các loại xe cơ giới, bao gồm cả xe mô tô đi vào.',
    category: 'Biển báo',
  ),
  Question(
    id: 5,
    content: 'Khi gặp đường giao nhau không có tín hiệu điều khiển, người lái xe phải nhường đường cho xe đến từ hướng nào?',
    options: [
      'Xe từ bên trái',
      'Xe từ bên phải',
      'Xe đi thẳng',
      'Xe có kích thước lớn hơn',
    ],
    correctIndex: 1,
    explanation: 'Tại nơi đường giao nhau không có báo hiệu đi theo vòng xuyến, phải nhường đường cho xe đến từ bên phải.',
    category: 'Quy tắc giao thông',
    isCritical: true,
  ),
  Question(
    id: 6,
    content: 'Nồng độ cồn trong máu tối đa cho phép đối với người điều khiển xe mô tô là bao nhiêu?',
    options: [
      '50 mg/100 ml máu',
      '80 mg/100 ml máu',
      '0 mg/100 ml máu (không được uống rượu bia)',
      '30 mg/100 ml máu',
    ],
    correctIndex: 2,
    explanation: 'Người điều khiển xe mô tô không được có nồng độ cồn trong máu (0 mg/100 ml máu) khi tham gia giao thông theo Luật GTĐB 2024.',
    category: 'Quy tắc giao thông',
    isCritical: true,
  ),
  Question(
    id: 7,
    content: 'Khoảng cách an toàn tối thiểu khi đi sau xe khác ở tốc độ 60 km/h là bao nhiêu mét?',
    options: ['20 m', '35 m', '55 m', '70 m'],
    correctIndex: 1,
    explanation: 'Ở tốc độ 60 km/h, khoảng cách an toàn tối thiểu là 35 m.',
    category: 'Tốc độ',
  ),
  Question(
    id: 8,
    content: 'Xe mô tô được phép chở tối đa bao nhiêu người (kể cả người lái)?',
    options: ['1 người', '2 người', '3 người', '4 người'],
    correctIndex: 1,
    explanation: 'Xe mô tô chỉ được chở tối đa 2 người, kể cả người lái (trừ trường hợp chở người bệnh cấp cứu, trẻ em dưới 7 tuổi có thể chở thêm 1 người).',
    category: 'Quy tắc giao thông',
  ),
  Question(
    id: 9,
    content: 'Đèn vàng tại ngã tư báo hiệu điều gì?',
    options: [
      'Được phép đi nhanh qua ngã tư',
      'Chuẩn bị dừng lại, trừ khi đã đi vào gần nơi dừng lại mà không thể dừng an toàn',
      'Phải dừng lại ngay lập tức',
      'Chuyển hướng sang phải',
    ],
    correctIndex: 1,
    explanation: 'Đèn vàng báo hiệu sắp chuyển sang đèn đỏ. Phải chuẩn bị dừng trước vạch dừng, trừ khi đã đi vào quá gần và không thể dừng an toàn.',
    category: 'Tín hiệu đèn',
  ),
  Question(
    id: 10,
    content: 'Khi muốn chuyển làn đường, người lái xe phải làm gì trước?',
    options: [
      'Tăng tốc để vượt qua nhanh',
      'Quan sát gương chiếu hậu và ra tín hiệu xin đường',
      'Bóp còi để thông báo',
      'Giảm tốc ngay lập tức',
    ],
    correctIndex: 1,
    explanation: 'Trước khi chuyển làn đường, phải quan sát gương chiếu hậu, xem khoảng cách xe phía sau và ra tín hiệu báo hướng rẽ ít nhất 30 m trước.',
    category: 'Quy tắc giao thông',
  ),

  // ===== BIỂN BÁO =====
  Question(
    id: 11,
    content: 'Biển báo hình tròn, nền đỏ, hình vẽ trắng có ý nghĩa gì?',
    options: [
      'Biển báo nguy hiểm',
      'Biển báo cấm',
      'Biển hiệu lệnh',
      'Biển chỉ dẫn',
    ],
    correctIndex: 1,
    explanation: 'Biển báo cấm có hình tròn, viền đỏ, nền trắng hoặc nền đỏ với hình vẽ màu đen hoặc trắng.',
    category: 'Biển báo',
  ),
  Question(
    id: 12,
    content: 'Biển báo hình tam giác, nền vàng, viền đỏ có ý nghĩa gì?',
    options: [
      'Biển báo cấm',
      'Biển hiệu lệnh',
      'Biển báo nguy hiểm',
      'Biển chỉ dẫn',
    ],
    correctIndex: 2,
    explanation: 'Biển báo nguy hiểm có hình tam giác đều, nền vàng, viền đỏ, hình vẽ màu đen.',
    category: 'Biển báo',
  ),
  Question(
    id: 13,
    content: 'Biển số "P" màu xanh có nghĩa là gì?',
    options: [
      'Cấm đỗ xe',
      'Cho phép đỗ xe',
      'Bãi đỗ xe có thu phí',
      'Khu vực đỗ xe riêng',
    ],
    correctIndex: 1,
    explanation: 'Biển chỉ dẫn bãi đỗ xe, nền xanh, chữ P trắng cho phép xe đỗ tại khu vực đó.',
    category: 'Biển báo',
  ),
  Question(
    id: 14,
    content: 'Gặp biển "Đường một chiều" bạn phải làm gì?',
    options: [
      'Đi ngược chiều mũi tên',
      'Đi theo chiều mũi tên chỉ dẫn',
      'Dừng lại và quan sát',
      'Đi ở làn bên phải',
    ],
    correctIndex: 1,
    explanation: 'Khi gặp biển đường một chiều, phải đi theo chiều mũi tên chỉ định.',
    category: 'Biển báo',
  ),
  Question(
    id: 15,
    content: 'Biển báo "Cấm vượt" có hiệu lực đến đâu?',
    options: [
      'Đến biển báo tiếp theo',
      'Đến hết đoạn đường',
      'Đến biển "Hết cấm vượt" hoặc hết đoạn đường có cắm biển',
      'Trong vòng 500 m',
    ],
    correctIndex: 2,
    explanation: 'Biển cấm vượt có hiệu lực từ vị trí đặt biển đến biển "Hết lệnh cấm vượt" hoặc hết đoạn đường có cắm biển.',
    category: 'Biển báo',
  ),

  // ===== KỸ NĂNG LÁI XE =====
  Question(
    id: 16,
    content: 'Khi phanh khẩn cấp trên đường trơn, bạn nên làm gì?',
    options: [
      'Bóp phanh trước thật mạnh',
      'Bóp phanh sau thật mạnh',
      'Nhả ga, bóp phanh nhẹ và đều cả hai phanh',
      'Tăng ga để ổn định xe',
    ],
    correctIndex: 2,
    explanation: 'Trên đường trơn, phải nhả ga, bóp phanh nhẹ nhàng và đều cả hai phanh để tránh bánh xe bị bó cứng gây ngã xe.',
    category: 'Kỹ thuật lái xe',
  ),
  Question(
    id: 17,
    content: 'Khi đi vào đường cong nguy hiểm, người lái xe phải làm gì?',
    options: [
      'Tăng tốc để qua nhanh',
      'Giữ nguyên tốc độ',
      'Giảm tốc độ trước khi vào đường cong',
      'Bấm còi liên tục',
    ],
    correctIndex: 2,
    explanation: 'Trước khi vào đường cong phải giảm tốc độ phù hợp, tránh phanh trong khi đang quẹo vì dễ mất thăng bằng.',
    category: 'Kỹ thuật lái xe',
  ),
  Question(
    id: 18,
    content: 'Khi lên dốc, xe nào được ưu tiên đường?',
    options: [
      'Xe xuống dốc',
      'Xe lên dốc',
      'Xe có kích thước lớn hơn',
      'Xe đến trước',
    ],
    correctIndex: 1,
    explanation: 'Trên đường dốc, xe lên dốc được ưu tiên. Xe xuống dốc phải nhường đường, lùi xe hoặc vào sát lề để nhường.',
    category: 'Quy tắc giao thông',
  ),
  Question(
    id: 19,
    content: 'Trong trường hợp nào xe mô tô được đi trên vỉa hè?',
    options: [
      'Khi đường quá đông',
      'Khi có sự cho phép của cảnh sát giao thông',
      'Không được phép trong bất kỳ trường hợp nào',
      'Khi muốn vào nhà hoặc nơi tập kết hàng',
    ],
    correctIndex: 2,
    explanation: 'Xe mô tô không được phép đi trên vỉa hè trong bất kỳ trường hợp nào.',
    category: 'Quy tắc giao thông',
    isCritical: true,
  ),
  Question(
    id: 20,
    content: 'Khi điều khiển xe mô tô ban đêm, bạn phải bật đèn gì?',
    options: [
      'Chỉ đèn xi nhan',
      'Đèn pha hoặc đèn cốt',
      'Chỉ đèn hậu',
      'Tất cả các đèn',
    ],
    correctIndex: 1,
    explanation: 'Khi đi ban đêm, xe mô tô phải bật đèn pha hoặc đèn cốt để chiếu sáng và để xe khác nhìn thấy.',
    category: 'Kỹ thuật lái xe',
  ),

  // ===== AN TOÀN GIAO THÔNG =====
  Question(
    id: 21,
    content: 'Hành vi nào sau đây bị nghiêm cấm khi điều khiển xe mô tô?',
    options: [
      'Bật đèn pha ban đêm',
      'Sử dụng điện thoại di động khi đang lái xe',
      'Giảm tốc độ khi trời mưa',
      'Đội mũ bảo hiểm',
    ],
    correctIndex: 1,
    explanation: 'Sử dụng điện thoại di động khi điều khiển xe là hành vi bị nghiêm cấm vì làm giảm sự tập trung và tăng nguy cơ tai nạn.',
    category: 'An toàn giao thông',
    isCritical: true,
  ),
  Question(
    id: 22,
    content: 'Khoảng cách tối thiểu khi vượt xe khác là bao nhiêu?',
    options: ['0.5 m', '1 m', '1.5 m', '2 m'],
    correctIndex: 1,
    explanation: 'Khi vượt xe, phải giữ khoảng cách ngang tối thiểu là 1 m với xe bị vượt để đảm bảo an toàn.',
    category: 'Quy tắc giao thông',
  ),
  Question(
    id: 23,
    content: 'Trường hợp nào sau đây xe mô tô không được vượt xe khác?',
    options: [
      'Khi đường thẳng và tầm nhìn tốt',
      'Khi đang lên dốc mà không nhìn rõ phía trước',
      'Khi đường rộng có vạch kẻ',
      'Khi xe phía trước đi quá chậm',
    ],
    correctIndex: 1,
    explanation: 'Không được vượt xe khi đang lên dốc mà không nhìn rõ phía trước vì nguy cơ gặp xe ngược chiều.',
    category: 'Quy tắc giao thông',
  ),
  Question(
    id: 24,
    content: 'Xe mô tô phải đi bên nào của đường?',
    options: [
      'Bên trái',
      'Giữa đường',
      'Bên phải theo chiều đi',
      'Tùy ý',
    ],
    correctIndex: 2,
    explanation: 'Xe mô tô phải đi bên phải theo chiều đi của mình, sát lề đường bên phải.',
    category: 'Quy tắc giao thông',
  ),
  Question(
    id: 25,
    content: 'Khi trời mưa, bạn phải điều chỉnh khoảng cách an toàn như thế nào?',
    options: [
      'Giữ nguyên khoảng cách bình thường',
      'Giảm khoảng cách vì đường trơn xe sẽ dừng nhanh hơn',
      'Tăng khoảng cách vì đường trơn quãng đường phanh dài hơn',
      'Không cần thay đổi',
    ],
    correctIndex: 2,
    explanation: 'Khi trời mưa đường trơn, quãng đường phanh dài hơn nên phải tăng khoảng cách an toàn với xe phía trước.',
    category: 'An toàn giao thông',
  ),

  // ===== XỬ PHẠT VÀ LUẬT =====
  Question(
    id: 26,
    content: 'Người điều khiển xe mô tô dưới bao nhiêu tuổi bị coi là vi phạm pháp luật?',
    options: ['14 tuổi', '16 tuổi', '18 tuổi', '20 tuổi'],
    correctIndex: 1,
    explanation: 'Người dưới 16 tuổi điều khiển xe mô tô có dung tích xi lanh từ 50cc trở lên là vi phạm pháp luật.',
    category: 'Pháp luật',
  ),
  Question(
    id: 27,
    content: 'Hành vi phóng nhanh vượt ẩu gây tai nạn nghiêm trọng có thể bị xử lý hình sự về tội gì?',
    options: [
      'Tội vi phạm hành chính',
      'Tội vi phạm quy định về điều khiển phương tiện giao thông đường bộ',
      'Tội cố ý gây thương tích',
      'Tội gây rối trật tự công cộng',
    ],
    correctIndex: 1,
    explanation: 'Phóng nhanh vượt ẩu gây tai nạn nghiêm trọng có thể bị truy cứu trách nhiệm hình sự về tội vi phạm quy định về điều khiển phương tiện giao thông đường bộ.',
    category: 'Pháp luật',
  ),
  Question(
    id: 28,
    content: 'Người điều khiển xe mô tô phải mang theo giấy tờ gì?',
    options: [
      'Chỉ cần CMND/CCCD',
      'Giấy phép lái xe và đăng ký xe',
      'Giấy phép lái xe, đăng ký xe và bảo hiểm xe',
      'Chỉ cần giấy phép lái xe',
    ],
    correctIndex: 2,
    explanation: 'Người điều khiển xe mô tô phải mang theo: Giấy phép lái xe, Giấy đăng ký xe, và Giấy chứng nhận bảo hiểm trách nhiệm dân sự còn hiệu lực.',
    category: 'Pháp luật',
  ),
  Question(
    id: 29,
    content: 'Trường hợp nào sau đây không phải là lỗi vi phạm giao thông?',
    options: [
      'Vượt đèn đỏ',
      'Không đội mũ bảo hiểm',
      'Dừng xe sát lề phải khi đèn đỏ',
      'Lạng lách, đánh võng',
    ],
    correctIndex: 2,
    explanation: 'Dừng xe sát lề phải khi đèn đỏ là hành vi đúng luật, không vi phạm.',
    category: 'Pháp luật',
  ),
  Question(
    id: 30,
    content: 'Khi bị cảnh sát giao thông yêu cầu dừng xe, bạn phải làm gì?',
    options: [
      'Tiếp tục đi vì mình không vi phạm',
      'Dừng xe ngay tại chỗ',
      'Dừng xe vào lề đường an toàn và xuất trình giấy tờ',
      'Bỏ chạy',
    ],
    correctIndex: 2,
    explanation: 'Khi bị yêu cầu dừng xe, phải dừng xe vào nơi an toàn (lề đường bên phải), tắt máy và xuất trình giấy tờ theo yêu cầu.',
    category: 'Pháp luật',
  ),

  // ===== CẤU TẠO XE =====
  Question(
    id: 31,
    content: 'Chức năng của nhớt (dầu nhờn) trong động cơ xe máy là gì?',
    options: [
      'Làm mát động cơ',
      'Làm sạch động cơ',
      'Bôi trơn các chi tiết và giảm ma sát',
      'Cung cấp năng lượng cho xe',
    ],
    correctIndex: 2,
    explanation: 'Dầu nhờn có chức năng bôi trơn các chi tiết chuyển động, giảm ma sát, làm mát và bảo vệ động cơ khỏi mài mòn.',
    category: 'Cấu tạo xe',
  ),
  Question(
    id: 32,
    content: 'Khi lốp xe bị xẹp đột ngột khi đang đi, bạn phải làm gì?',
    options: [
      'Phanh gấp ngay lập tức',
      'Tăng tốc để về bến gần nhất',
      'Giữ vững tay lái, từ từ giảm tốc và dừng xe vào lề',
      'Tiếp tục đi bình thường',
    ],
    correctIndex: 2,
    explanation: 'Khi lốp xẹp đột ngột, không phanh gấp vì có thể mất lái. Hãy giữ vững tay lái, từ từ nhả ga giảm tốc và dừng xe an toàn vào lề đường.',
    category: 'Kỹ thuật lái xe',
  ),
  Question(
    id: 33,
    content: 'Khi nào cần kiểm tra và thay nhớt xe máy?',
    options: [
      'Sau mỗi 1,000 km hoặc 1 tháng',
      'Sau mỗi 2,000-3,000 km hoặc theo khuyến cáo nhà sản xuất',
      'Sau mỗi 10,000 km',
      'Chỉ khi xe có vấn đề',
    ],
    correctIndex: 1,
    explanation: 'Thông thường nên thay nhớt xe máy sau mỗi 2,000-3,000 km hoặc theo khuyến cáo của nhà sản xuất trong sách hướng dẫn sử dụng.',
    category: 'Cấu tạo xe',
  ),
  Question(
    id: 34,
    content: 'Áp suất lốp xe không đủ ảnh hưởng như thế nào đến xe?',
    options: [
      'Tăng độ bám đường',
      'Giảm tiêu hao nhiên liệu',
      'Tăng nguy cơ lốp nổ và tăng tiêu hao nhiên liệu',
      'Không ảnh hưởng đáng kể',
    ],
    correctIndex: 2,
    explanation: 'Lốp xe thiếu áp suất làm tăng nguy cơ nổ lốp, giảm khả năng điều khiển và tăng tiêu hao nhiên liệu.',
    category: 'Cấu tạo xe',
  ),
  Question(
    id: 35,
    content: 'Khi phanh xe, đèn phanh (đèn hậu) phát sáng có tác dụng gì?',
    options: [
      'Trang trí cho xe đẹp hơn',
      'Cảnh báo cho xe phía sau biết xe đang phanh/giảm tốc',
      'Chiếu sáng phía sau xe',
      'Tiết kiệm nhiên liệu',
    ],
    correctIndex: 1,
    explanation: 'Đèn phanh (stop light) sáng lên khi bóp phanh để cảnh báo cho xe phía sau biết xe đang phanh, giảm tốc.',
    category: 'Cấu tạo xe',
  ),

  // ===== TÌNH HUỐNG GIAO THÔNG =====
  Question(
    id: 36,
    content: 'Tại ngã tư có đèn tín hiệu, đèn xanh bật nhưng có người đi bộ đang băng qua đường, bạn phải làm gì?',
    options: [
      'Tiếp tục đi nhanh qua vì đèn đã xanh',
      'Bóp còi to để người đi bộ tránh sang',
      'Dừng lại hoặc giảm tốc nhường cho người đi bộ',
      'Lách qua phía sau người đi bộ',
    ],
    correctIndex: 2,
    explanation: 'Dù đèn xanh, người lái xe vẫn phải nhường đường cho người đi bộ đang băng qua đường an toàn. Người đi bộ luôn được ưu tiên.',
    category: 'Tình huống giao thông',
    isCritical: true,
  ),
  Question(
    id: 37,
    content: 'Khi đi vào vùng có sương mù dày, bạn phải làm gì?',
    options: [
      'Tắt đèn để tiết kiệm điện',
      'Bật đèn pha để nhìn xa hơn',
      'Giảm tốc độ, bật đèn cốt và đèn sương mù (nếu có)',
      'Tiếp tục đi bình thường',
    ],
    correctIndex: 2,
    explanation: 'Trong điều kiện sương mù: giảm tốc độ, bật đèn cốt (không dùng đèn pha vì ánh sáng phản chiếu làm mờ tầm nhìn), bật đèn sương mù nếu có.',
    category: 'An toàn giao thông',
  ),
  Question(
    id: 38,
    content: 'Khi xe phía trước bạn bật xi nhan xin rẽ trái, bạn phải làm gì?',
    options: [
      'Vượt qua bên trái xe đó',
      'Vượt qua bên phải xe đó',
      'Giảm tốc và chờ xe đó rẽ xong',
      'Bóp còi và tiếp tục đi',
    ],
    correctIndex: 2,
    explanation: 'Khi xe trước bật xi nhan rẽ trái, không được vượt bên trái vì xe đó sắp rẽ. Phải giảm tốc chờ xe đó rẽ xong mới đi tiếp.',
    category: 'Tình huống giao thông',
  ),
  Question(
    id: 39,
    content: 'Khi gặp xe cứu thương đang hú còi, bạn phải làm gì?',
    options: [
      'Tiếp tục đi bình thường',
      'Dừng xe lại hoàn toàn',
      'Tránh sang bên phải, giảm tốc hoặc dừng để nhường đường',
      'Đi theo xe cứu thương',
    ],
    correctIndex: 2,
    explanation: 'Phải tránh sang bên phải, giảm tốc hoặc dừng lại để nhường đường cho xe ưu tiên (cứu thương, cứu hỏa, cảnh sát) đang làm nhiệm vụ.',
    category: 'Tình huống giao thông',
    isCritical: true,
  ),
  Question(
    id: 40,
    content: 'Bạn đang đi đúng làn đường, một xe máy từ ngõ lao ra đường trước mặt. Bạn phải làm gì?',
    options: [
      'Tiếp tục đi vì bạn đang đi đúng luật',
      'Bóp còi to và tiếp tục đi',
      'Phanh khẩn cấp, tránh sang bên phải nếu có thể',
      'Tăng tốc để thoát qua',
    ],
    correctIndex: 2,
    explanation: 'Trong tình huống nguy hiểm, dù đang đúng luật vẫn phải ưu tiên tránh tai nạn. Phanh khẩn cấp và tránh sang phải nếu an toàn.',
    category: 'Tình huống giao thông',
  ),
];

// Lấy câu hỏi ngẫu nhiên cho đề thi
List<Question> generateExam({int count = 25}) {
  final shuffled = List<Question>.from(questionBank)..shuffle();

  // Đảm bảo có ít nhất 3 câu điểm liệt
  final criticalQuestions = shuffled.where((q) => q.isCritical).take(3).toList();
  final normalQuestions = shuffled.where((q) => !q.isCritical).take(count - criticalQuestions.length).toList();

  final examQuestions = [...criticalQuestions, ...normalQuestions]..shuffle();
  return examQuestions.take(count).toList();
}
